spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socket
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost               # Redis가 실행 중인 호스트
    port: 6379                    # Redis 포트
    password: 1234
    timeout: 60000                # 연결 제한 시간


springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /api/**  # swagger-ui? ??? api? ????? ??

jwt:
  header: Authorization
  secret: dfklWWHObhUWHEJKHhkjHWKXEHWUIEHXWUIWjhkjHJKWHEJWKeKEhjhKJHEWlhjkjklewkjkljkljewqnnjkbctjkwbtek
  token-validity-in-seconds: 86400

server:
  address: 0.0.0.0
  port: 8082

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.core.env: DEBUG
      org.springframework.cloud.aws: DEBUG
